### ISSUE TITLE
Giving error while loading model, when trying to train on generation

### ISSUE THREAD

**Issue by ManiMukeshReddyNukal** [reddy-lab-code-research/StructCoder#1]
getting this error, when trying to load model, can you provide arguments uesd to load the model for which checkpoint has been provided??
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/StructCoder/inference.py", line 473, in <module>
    main()
  File "/content/drive/MyDrive/StructCoder/inference.py", line 433, in main
    my_dict['ast_path_head.weight'][i::len(pt_node_types), :] = pt_dict['ast_path_head.weight'][i::len(pt_node_types), :]
RuntimeError: The expanded size of the tensor (5) must match the existing size (12) at non-singleton dimension 0.  Target sizes: [5, 128].  Tensor sizes: [12, 128]
```

**Comment by sindhura97** [comment]
Hi, We have updated the codes and the pretrained checkpoint. This error should disappear now.

**Comment by kris-31** [comment]
how to just run the pretrained model?
i downloaded the weights and moved to saved_models/pretrain dir.
i want to run and test with some inputs before fine tuning .
KINDLY HELP ME
